### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by zingon** [zingon/gergel.cz#34]
Při zmenšení okna otevření a zavření menu a potom znovu zvětšení okna se nezobrazí odkazy. Bude to asi tim že ty odkazy jsou stále zavřený.

**Comment by lHalali** [comment]
No a? Na mobilu si těžko budeš hrát s oknem a na desktopu si nikdo s oknem webu taky nehraje  :dancer:

**Comment by zingon** [comment]
Jak myslíš.
