### ISSUE TITLE
Oprava fontu

### ISSUE THREAD

**Issue by zingon** [zingon/gergel.cz#7]
![snimek obrazovky porizeny 2015-03-05 20 18 11](https://cloud.githubusercontent.com/assets/4988255/6512515/d59ae9fa-c374-11e4-91f5-c41602dbb2f3.png) 
Posral se font v hlavičce bude to asi zas nedostatkem znaků

**Comment by lHalali** [comment]
Snad to funguje, na windows to neblbne.
